### ISSUE TITLE
Add post build hook

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/sti-perl#70]
Add an example build hook to run unit tests as part of the build.

:thought_balloon: I tried doing so myself but couldn't get it working without friction, so deferring it for later or someone else.

The hook shall be added to the BuildConfigs of our templates:

```diff
+        "postCommit": {
+          "script": "perl -Iextlib/lib/perl5 t/*"
+        }
```

I am not sure about the right one-liner to run unit tests.

**Comment by mfojtik** [comment]
@ppisar FYI

**Comment by ppisar** [comment]
The tool for executing perl tests is called *prove*. It can be found in *-perl-Test-Harness package or  by installing Test::Harness module from CPAN. It automatically searches tests in t/*.t, so the only think you need to do pass is a correct -I argument to point to the directory where your application installed the modules.

If you want to run tests of modules installed from CPAN, setting ENABLE_CPAN_TEST environment variable to *true* should be enough.

But I have no idea what *BuildConfigs of our templates* is.

**Comment by rhcarvalho** [comment]
@ppisar for the code in this repository, what are the steps to run the tests under `t/`, if you were developing this app?

Are the existing tests minimally reasonable? They seem to be coming from some scaffolding, not hand written.

**Comment by rhcarvalho** [comment]
I messed up and created this in the wrong repo.
Migrated to the appropriate place :arrow_right: https://github.com/openshift/dancer-ex/issues/29
